CREATE TABLE EMPLOYEE(
  EMPLOYEE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME								VARCHAR(30) NOT NULL,
  EMAIL                             VARCHAR(50) NOT NULL,
  DEPARTMENT                        VARCHAR(50) NOT NULL
);
